##### Importing inportant librarries

In [162]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

##### Loading the dataset

In [163]:
df=pd.read_csv('../data/loan_dataset.csv')

In [164]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

- As Loan_ID has no importance in the process of Approval or Rejection ,we are directly dropping this column

In [165]:
df.drop(labels='Loan_ID',inplace=True,axis=1,errors='raise')

In [166]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

##### Seperate the target(y) and input_variable(X)
- here Loan_Status is the target variable(y)
- and df.columns except Loan_Status are the inputs
- inputvariable(X) df without target column

In [167]:
y=df['Loan_Status']

In [168]:
y.head()

0    Y
1    N
2    Y
3    Y
4    Y
Name: Loan_Status, dtype: object

In [169]:
X=df.drop(labels='Loan_Status',errors='raise',axis=1)

In [170]:
X.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban

In [171]:
df['Loan_Status'].value_counts()

Loan_Status
Y    422
N    192
Name: count, dtype: int64

##### Train test split
- here the data is very less ,compared to real world
- As we already know dataset is imbalanced ,we need to split stratifiedly
- What is this stratify??
- if training data have more datapoints in class_1,and few data points in class_0,our model may tend to biased towards dominant class
- So if we split stratifiedly ,we can prevent this by splitting data in such a way both training and testing data have similar ratio of no.of Datapoints of class_1 to class_0
- This confirms ,our model do not show any bias towards one of the classes

In [173]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [174]:
print(df.shape)

(614, 12)

In [175]:
print(X_train .shape)
print(y_train.shape)

(491, 11)
(491,)

In [176]:
print(X_test.shape)
print(y_test.shape)

(123, 11)
(123,)

In [177]:
y_test.value_counts()

Loan_Status
Y    85
N    38
Name: count, dtype: int64

In [178]:
temp=85/38
print(temp)

2.236842105263158

In [179]:
y_train.value_counts()

Loan_Status
Y    337
N    154
Name: count, dtype: int64

In [180]:
temp2=337/154
print(temp2)

2.188311688311688

In [181]:
X_train.isnull().sum()

Gender               11
Married               3
Dependents            8
Education             0
Self_Employed        27
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           20
Loan_Amount_Term     12
Credit_History       43
Property_Area         0
dtype: int64

In [182]:
for col in X_train.columns:
    if col not in ['ApplicantIncome','CoapplicantIncome','LoanAmount']:
        print(col,X_train[col].unique())
        print(X_train[col].value_counts())
        print("--------")

Gender ['Male' 'Female' nan]
Gender
Male      393
Female     87
Name: count, dtype: int64
--------
Married ['No' 'Yes' nan]
Married
Yes    319
No     169
Name: count, dtype: int64
--------
Dependents ['0' '1' '2' nan '3+']
Dependents
0     276
1      85
2      83
3+     39
Name: count, dtype: int64
--------
Education ['Graduate' 'Not Graduate']
Education
Graduate        380
Not Graduate    111
Name: count, dtype: int64
--------
Self_Employed ['No' 'Yes' nan]
Self_Employed
No     398
Yes     66
Name: count, dtype: int64
--------
Loan_Amount_Term [360. 180.  nan  84. 300. 240.  60. 480.  12. 120.  36.]
Loan_Amount_Term
360.0    409
180.0     35
480.0     11
300.0     10
240.0      4
84.0       3
60.0       2
120.0      2
36.0       2
12.0       1
Name: count, dtype: int64
--------
Credit_History [ 1.  0. nan]
Credit_History
1.0    381
0.0     67
Name: count, dtype: int64
--------
Property_Area ['Urban' 'Semiurban' 'Rural']
Property_Area
Semiurban    184
Urban        162
Rural        145
Name: count, dtype: int64
--------

In [183]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 491 entries, 154 to 354
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             480 non-null    object
 1   Married            488 non-null    object
 2   Dependents         483 non-null    object
 3   Education          491 non-null    object
 4   Self_Employed      464 non-null    object
 5   ApplicantIncome    491 non-null    int64
 6   CoapplicantIncome  491 non-null    float64
 7   LoanAmount         471 non-null    float64
 8   Loan_Amount_Term   479 non-null    float64
 9   Credit_History     448 non-null    float64
 10  Property_Area      491 non-null    object
dtypes: float64(4), int64(1), object(6)
memory usage: 46.0+ KB

In [184]:
X_train['Dependents'] = X_train['Dependents'].replace(to_replace='3+', value='3')

In [185]:
X_test['Dependents'] = X_test['Dependents'].replace('3+','3')

In [186]:
X_test['Dependents'].unique()

array(['0', '1', '3', nan, '2'], dtype=object)

In [187]:
X_train['Dependents'].unique()

array(['0', '1', '2', nan, '3'], dtype=object)

##### Changing datatype of dependents Column
- intilaly its a string ,we are converting it into float in both training and test data

In [188]:
X_train['Dependents'] = X_train['Dependents'].astype('float64')

In [189]:
X_test['Dependents']=X_test['Dependents'].astype('float64')

##### Handling missing values
- for categorical features ,mode is good
- for numerical feature ,median imputation is best ,,as median is robuts to outliers

In [190]:
Gender_mode=X_train['Gender'].mode()[0]
Married_mode=X_train['Married'].mode()[0]
Self_Employed_mode=X_train['Self_Employed'].mode()[0]
Dependents_mode=X_train['Dependents'].mode()[0]
Credit_History_mode=X_train['Credit_History'].mode()[0]
Loan_Amount_Term_mode=X_train['Loan_Amount_Term'].mode()[0]

LoanAmount_median=X_train['LoanAmount'].median()

##### Target variable

In [191]:
Loan_Status_mode=y_train.mode()[0]

In [192]:
print(Dependents_mode)

0.0

In [193]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 491 entries, 154 to 354
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             480 non-null    object
 1   Married            488 non-null    object
 2   Dependents         483 non-null    float64
 3   Education          491 non-null    object
 4   Self_Employed      464 non-null    object
 5   ApplicantIncome    491 non-null    int64
 6   CoapplicantIncome  491 non-null    float64
 7   LoanAmount         471 non-null    float64
 8   Loan_Amount_Term   479 non-null    float64
 9   Credit_History     448 non-null    float64
 10  Property_Area      491 non-null    object
dtypes: float64(5), int64(1), object(5)
memory usage: 46.0+ KB

##### Filling missing values
- In both training and testing data ,we need to impute our values computed from training data to ensure there is no data leakage 
- And then it will be robust to new unknown datapoints also

In [194]:
X_train['Gender']=X_train['Gender'].fillna(Gender_mode)
X_train['Married']=X_train['Married'].fillna(Married_mode)
X_train['Dependents']=X_train['Dependents'].fillna(Dependents_mode)
X_train['Self_Employed']=X_train['Self_Employed'].fillna(Self_Employed_mode)

X_train['Credit_History']=X_train['Credit_History'].fillna(Credit_History_mode)
X_train['Loan_Amount_Term']=X_train['Loan_Amount_Term'].fillna(Loan_Amount_Term_mode)



X_train['LoanAmount'] = X_train['LoanAmount'].fillna(LoanAmount_median)

In [195]:
y_train=y_train.fillna(Loan_Status_mode)

In [196]:
X_train.head(10)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
154,Male,No,0.0,Graduate,No,3254,0.0,50.0,360.0,1.0,Urban
239,Male,Yes,1.0,Graduate,No,3315,0.0,96.0,360.0,1.0,Semiurban
448,Male,Yes,2.0,Graduate,No,3340,1710.0,150.0,360.0,0.0,Rural
471,Male,Yes,1.0,Not Graduate,No,2653,1500.0,113.0,180.0,0.0,Rural
273,Male,Yes,0.0,Graduate,No,2620,2223.0,150.0,360.0,1.0,Semiurban
71,Male,Yes,2.0,Not Graduate,Yes,1875,1875.0,97.0,360.0,1.0,Semiurban
590,Male,Yes,0.0,Graduate,No,3000,3416.0,56.0,180.0,1.0,Semiurban
187,Male,Yes,0.0,Graduate,No,2383,2138.0,58.0,360.0,1.0,Rural
404,Female,No,0.0,Graduate,Yes,7441,0.0,194.0,360.0,1.0,Rural
159,Male,Yes,0.0,Graduate,No,4583,5625.0,255.0,360.0,1.0,Semiurban

In [197]:
X_train.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [198]:
X_test['Gender']=X_test['Gender'].fillna(Gender_mode)
X_test['Married']=X_test['Married'].fillna(Married_mode)
X_test['Self_Employed']=X_test['Self_Employed'].fillna(Loan_Status_mode)
X_test['Dependents']=X_test['Dependents'].fillna(Dependents_mode)
X_test['Credit_History']=X_test['Credit_History'].fillna(Credit_History_mode)
X_test['Loan_Amount_Term']=X_test['Loan_Amount_Term'].fillna(Loan_Amount_Term_mode)



X_test['LoanAmount'] = X_test['LoanAmount'].fillna(LoanAmount_median)

In [199]:
X_test.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
150,Male,No,0.0,Graduate,No,6277,0.0,118.0,360.0,0.0,Rural
559,Female,Yes,0.0,Graduate,No,4180,2306.0,182.0,360.0,1.0,Semiurban
598,Male,Yes,0.0,Graduate,Yes,9963,0.0,180.0,360.0,1.0,Rural
235,Male,Yes,1.0,Graduate,No,5500,1260.0,170.0,360.0,1.0,Rural
145,Female,Yes,0.0,Graduate,No,2330,4486.0,100.0,360.0,1.0,Semiurban

In [200]:
X_test.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [201]:
X_test.head(10)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
150,Male,No,0.0,Graduate,No,6277,0.0,118.0,360.0,0.0,Rural
559,Female,Yes,0.0,Graduate,No,4180,2306.0,182.0,360.0,1.0,Semiurban
598,Male,Yes,0.0,Graduate,Yes,9963,0.0,180.0,360.0,1.0,Rural
235,Male,Yes,1.0,Graduate,No,5500,1260.0,170.0,360.0,1.0,Rural
145,Female,Yes,0.0,Graduate,No,2330,4486.0,100.0,360.0,1.0,Semiurban
191,Male,No,0.0,Graduate,No,12000,0.0,164.0,360.0,1.0,Semiurban
557,Male,Yes,3.0,Graduate,Yes,10139,0.0,260.0,360.0,1.0,Semiurban
470,Male,Yes,1.0,Graduate,Yes,3450,2079.0,162.0,360.0,1.0,Semiurban
88,Male,No,0.0,Graduate,No,8566,0.0,210.0,360.0,1.0,Urban
386,Male,No,0.0,Not Graduate,No,2346,1600.0,132.0,360.0,1.0,Semiurban

##### Creating our useful columns
- TotalIncome
- ApplicantIncome + CoapplicantIncome

- Loan_Income_Ratio
- ( LoanAmount * 1000 ) /TotalIncome

In [202]:
X_train['TotalIncome'] = X_train['ApplicantIncome'] + X_train['CoapplicantIncome']
X_train['Loan_Income_Ratio']=(X_train['LoanAmount']*1000)/X_train['TotalIncome']

In [204]:
X_train.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,TotalIncome,Loan_Income_Ratio
154,Male,No,0.0,Graduate,No,3254,0.0,50.0,360.0,1.0,Urban,3254.0,15.365704
239,Male,Yes,1.0,Graduate,No,3315,0.0,96.0,360.0,1.0,Semiurban,3315.0,28.959276
448,Male,Yes,2.0,Graduate,No,3340,1710.0,150.0,360.0,0.0,Rural,5050.0,29.702970
471,Male,Yes,1.0,Not Graduate,No,2653,1500.0,113.0,180.0,0.0,Rural,4153.0,27.209246
273,Male,Yes,0.0,Graduate,No,2620,2223.0,150.0,360.0,1.0,Semiurban,4843.0,30.972538

In [205]:
X_test['TotalIncome'] = X_test['ApplicantIncome'] + X_test['CoapplicantIncome']
X_test['Loan_Income_Ratio']=(X_test['LoanAmount']*1000)/X_test['TotalIncome']

In [207]:
print(X_train.shape)
print(X_test.shape)

(491, 13)
(123, 13)

##### Encoding Step
- As our model cant understand Strings like 'Male','Female','Yes','No' and so on 
- We usually convert them into numbers
- Here ,if the feature is binary ,we will map it directly using binary digits 1 and 0
- if column having more than 2 values ,going to do ONeHotEncoding
- This is for categorical variables

In [208]:
X_train.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'TotalIncome',
       'Loan_Income_Ratio'],
      dtype='object')

##### binary variables 
- NO NEED TO CREATE NEW COLUMNS,WE CAN JUST MODIFY COLUMN BY REPLACING WITH BINARY DIGITS
- 'Gender' --> Male_(!) and Female(0)
- 'Married' --> Yes(1) and No(0)
- 'Education' --> Graduate(1) and Not Graduate(0)
- 'Loan_Status'---> Yes(1) and No(0)

##### Gender
- Male and __Male are different here
- So we need to clean the column first ,and then map

In [209]:
X_train['Gender'].tail(10)

360    Female
383      Male
297    Female
447      Male
117      Male
222      Male
349      Male
26       Male
96     Female
354    Female
Name: Gender, dtype: object

In [210]:
X_train['Gender'] = X_train['Gender'].str.strip()
X_train['Gender'] = X_train['Gender'].map({'Male':1,'Female':0})

In [211]:
X_train.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,TotalIncome,Loan_Income_Ratio
154,1,No,0.0,Graduate,No,3254,0.0,50.0,360.0,1.0,Urban,3254.0,15.365704
239,1,Yes,1.0,Graduate,No,3315,0.0,96.0,360.0,1.0,Semiurban,3315.0,28.959276
448,1,Yes,2.0,Graduate,No,3340,1710.0,150.0,360.0,0.0,Rural,5050.0,29.702970
471,1,Yes,1.0,Not Graduate,No,2653,1500.0,113.0,180.0,0.0,Rural,4153.0,27.209246
273,1,Yes,0.0,Graduate,No,2620,2223.0,150.0,360.0,1.0,Semiurban,4843.0,30.972538

In [212]:
X_test['Gender'] = X_test['Gender'].str.strip()
X_test['Gender'] = X_test['Gender'].map({'Male':1,'Female':0})

In [213]:
X_test.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,TotalIncome,Loan_Income_Ratio
150,1,No,0.0,Graduate,No,6277,0.0,118.0,360.0,0.0,Rural,6277.0,18.798789
559,0,Yes,0.0,Graduate,No,4180,2306.0,182.0,360.0,1.0,Semiurban,6486.0,28.060438
598,1,Yes,0.0,Graduate,Yes,9963,0.0,180.0,360.0,1.0,Rural,9963.0,18.066847
235,1,Yes,1.0,Graduate,No,5500,1260.0,170.0,360.0,1.0,Rural,6760.0,25.147929
145,0,Yes,0.0,Graduate,No,2330,4486.0,100.0,360.0,1.0,Semiurban,6816.0,14.671362

##### Married 
- Yes  ---> 1

- No   ---> 0

- clean the column
- replace with binary digits

In [214]:
X_train['Married'].head(10)

154     No
239    Yes
448    Yes
471    Yes
273    Yes
71     Yes
590    Yes
187    Yes
404     No
159    Yes
Name: Married, dtype: object

In [215]:
X_train['Married'] = X_train['Married'].str.strip()
X_train['Married'] = X_train['Married'].map({'Yes':1,'No':0})

In [216]:
X_train.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,TotalIncome,Loan_Income_Ratio
154,1,0,0.0,Graduate,No,3254,0.0,50.0,360.0,1.0,Urban,3254.0,15.365704
239,1,1,1.0,Graduate,No,3315,0.0,96.0,360.0,1.0,Semiurban,3315.0,28.959276
448,1,1,2.0,Graduate,No,3340,1710.0,150.0,360.0,0.0,Rural,5050.0,29.702970
471,1,1,1.0,Not Graduate,No,2653,1500.0,113.0,180.0,0.0,Rural,4153.0,27.209246
273,1,1,0.0,Graduate,No,2620,2223.0,150.0,360.0,1.0,Semiurban,4843.0,30.972538

In [217]:
X_test['Married'] = X_test['Married'].str.strip()
X_test['Married'] = X_test['Married'].map({'Yes':1,'No':0})

In [218]:
X_test.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,TotalIncome,Loan_Income_Ratio
150,1,0,0.0,Graduate,No,6277,0.0,118.0,360.0,0.0,Rural,6277.0,18.798789
559,0,1,0.0,Graduate,No,4180,2306.0,182.0,360.0,1.0,Semiurban,6486.0,28.060438
598,1,1,0.0,Graduate,Yes,9963,0.0,180.0,360.0,1.0,Rural,9963.0,18.066847
235,1,1,1.0,Graduate,No,5500,1260.0,170.0,360.0,1.0,Rural,6760.0,25.147929
145,0,1,0.0,Graduate,No,2330,4486.0,100.0,360.0,1.0,Semiurban,6816.0,14.671362

##### Education
- Graduate ---> 1
- Not Graduate ---> 0

In [219]:
X_train['Education'].head(10)

154        Graduate
239        Graduate
448        Graduate
471    Not Graduate
273        Graduate
71     Not Graduate
590        Graduate
187        Graduate
404        Graduate
159        Graduate
Name: Education, dtype: object

In [220]:
X_train['Education'] = X_train['Education'].str.strip()
X_train['Education'] = X_train['Education'].map({'Graduate':1,'Not Graduate':0})

In [221]:
X_train.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,TotalIncome,Loan_Income_Ratio
154,1,0,0.0,1,No,3254,0.0,50.0,360.0,1.0,Urban,3254.0,15.365704
239,1,1,1.0,1,No,3315,0.0,96.0,360.0,1.0,Semiurban,3315.0,28.959276
448,1,1,2.0,1,No,3340,1710.0,150.0,360.0,0.0,Rural,5050.0,29.702970
471,1,1,1.0,0,No,2653,1500.0,113.0,180.0,0.0,Rural,4153.0,27.209246
273,1,1,0.0,1,No,2620,2223.0,150.0,360.0,1.0,Semiurban,4843.0,30.972538

In [222]:
X_test['Education'] = X_test['Education'].str.strip()
X_test['Education'] = X_test['Education'].map({'Graduate':1,'Not Graduate':0})

In [223]:
X_test.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,TotalIncome,Loan_Income_Ratio
150,1,0,0.0,1,No,6277,0.0,118.0,360.0,0.0,Rural,6277.0,18.798789
559,0,1,0.0,1,No,4180,2306.0,182.0,360.0,1.0,Semiurban,6486.0,28.060438
598,1,1,0.0,1,Yes,9963,0.0,180.0,360.0,1.0,Rural,9963.0,18.066847
235,1,1,1.0,1,No,5500,1260.0,170.0,360.0,1.0,Rural,6760.0,25.147929
145,0,1,0.0,1,No,2330,4486.0,100.0,360.0,1.0,Semiurban,6816.0,14.671362

##### Self_Employed
- Yes ---> 1
- No ----> 0

In [224]:
X_train['Self_Employed'].head(10)

154     No
239     No
448     No
471     No
273     No
71     Yes
590     No
187     No
404    Yes
159     No
Name: Self_Employed, dtype: object

In [226]:
X_train['Self_Employed'] = X_train['Self_Employed'].str.strip()
X_train['Self_Employed'] = X_train['Self_Employed'].map({'Yes':1,'No':0})

In [227]:
X_train.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,TotalIncome,Loan_Income_Ratio
154,1,0,0.0,1,0,3254,0.0,50.0,360.0,1.0,Urban,3254.0,15.365704
239,1,1,1.0,1,0,3315,0.0,96.0,360.0,1.0,Semiurban,3315.0,28.959276
448,1,1,2.0,1,0,3340,1710.0,150.0,360.0,0.0,Rural,5050.0,29.702970
471,1,1,1.0,0,0,2653,1500.0,113.0,180.0,0.0,Rural,4153.0,27.209246
273,1,1,0.0,1,0,2620,2223.0,150.0,360.0,1.0,Semiurban,4843.0,30.972538

In [228]:
X_test['Self_Employed'] = X_test['Self_Employed'].str.strip()
X_test['Self_Employed'] = X_test['Self_Employed'].map({'Yes':1,'No':0})

In [229]:
X_test.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,TotalIncome,Loan_Income_Ratio
150,1,0,0.0,1,0.0,6277,0.0,118.0,360.0,0.0,Rural,6277.0,18.798789
559,0,1,0.0,1,0.0,4180,2306.0,182.0,360.0,1.0,Semiurban,6486.0,28.060438
598,1,1,0.0,1,1.0,9963,0.0,180.0,360.0,1.0,Rural,9963.0,18.066847
235,1,1,1.0,1,0.0,5500,1260.0,170.0,360.0,1.0,Rural,6760.0,25.147929
145,0,1,0.0,1,0.0,2330,4486.0,100.0,360.0,1.0,Semiurban,6816.0,14.671362

In [230]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 123 entries, 150 to 373
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             123 non-null    int64
 1   Married            123 non-null    int64
 2   Dependents         123 non-null    float64
 3   Education          123 non-null    int64
 4   Self_Employed      118 non-null    float64
 5   ApplicantIncome    123 non-null    int64
 6   CoapplicantIncome  123 non-null    float64
 7   LoanAmount         123 non-null    float64
 8   Loan_Amount_Term   123 non-null    float64
 9   Credit_History     123 non-null    float64
 10  Property_Area      123 non-null    object
 11  TotalIncome        123 non-null    float64
 12  Loan_Income_Ratio  123 non-null    float64
dtypes: float64(8), int64(4), object(1)
memory usage: 13.5+ KB

##### Encoding for target variable in both train and test data
- Binary Encoding
- Y ----> 1
- N ----> 0

In [231]:
y_train.head()

154    Y
239    Y
448    N
471    N
273    Y
Name: Loan_Status, dtype: object

In [232]:


y_train= y_train.str.strip()
y_train = y_train.map({'Y':1,'N':0})

In [233]:
y_train.head()

154    1
239    1
448    0
471    0
273    1
Name: Loan_Status, dtype: int64

In [234]:
y_test= y_test.str.strip()
y_test = y_test.map({'Y':1,'N':0})

In [235]:
y_test.head()

150    0
559    1
598    1
235    1
145    1
Name: Loan_Status, dtype: int64

##### OneHotEncoding
- Depemdents
- Property_Area
- Loan_Amount_Term

In [236]:
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

##### fit on train data

In [237]:
encoder.fit(X_train[['Dependents','Property_Area','Loan_Amount_Term']])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [238]:
encoded_train = encoder.transform(X_train[['Dependents','Property_Area','Loan_Amount_Term']])

In [239]:
encoded_train_df=pd.DataFrame(encoded_train, columns=encoder.get_feature_names_out())
encoded_train_df

,Dependents_0.0,Dependents_1.0,Dependents_2.0,Dependents_3.0,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Loan_Amount_Term_12.0,Loan_Amount_Term_36.0,Loan_Amount_Term_60.0,Loan_Amount_Term_84.0,Loan_Amount_Term_120.0,Loan_Amount_Term_180.0,Loan_Amount_Term_240.0,Loan_Amount_Term_300.0,Loan_Amount_Term_360.0,Loan_Amount_Term_480.0
0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
487,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
488,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
489,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
490,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [240]:
encoded_test = encoder.transform(X_test[['Dependents','Property_Area','Loan_Amount_Term']])

In [241]:
encoded_test_df=pd.DataFrame(encoded_test, columns=encoder.get_feature_names_out())
encoded_test_df

,Dependents_0.0,Dependents_1.0,Dependents_2.0,Dependents_3.0,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Loan_Amount_Term_12.0,Loan_Amount_Term_36.0,Loan_Amount_Term_60.0,Loan_Amount_Term_84.0,Loan_Amount_Term_120.0,Loan_Amount_Term_180.0,Loan_Amount_Term_240.0,Loan_Amount_Term_300.0,Loan_Amount_Term_360.0,Loan_Amount_Term_480.0
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
119,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
120,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
121,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
122,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

##### Dropping the Old Columns
- We have OneHotEncoded Dependents into 4 categories,so we need to drop our previous Dependents column
- In the same way ,need to drop Property_Area and Loan_Amount_Term
- Dependents ----> 4 
- Property_Area ----> 3
- Loan_Amount_Term ----> 10

In [242]:
X_train.drop(labels=['Dependents','Property_Area','Loan_Amount_Term'],inplace=True,axis=1)

In [243]:
X_train.head()

,Gender,Married,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Credit_History,TotalIncome,Loan_Income_Ratio
154,1,0,1,0,3254,0.0,50.0,1.0,3254.0,15.365704
239,1,1,1,0,3315,0.0,96.0,1.0,3315.0,28.959276
448,1,1,1,0,3340,1710.0,150.0,0.0,5050.0,29.702970
471,1,1,0,0,2653,1500.0,113.0,0.0,4153.0,27.209246
273,1,1,1,0,2620,2223.0,150.0,1.0,4843.0,30.972538

In [244]:
X_test.drop(labels=['Dependents','Property_Area','Loan_Amount_Term'],inplace=True,axis=1)

In [245]:
X_test.head()

,Gender,Married,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Credit_History,TotalIncome,Loan_Income_Ratio
150,1,0,1,0.0,6277,0.0,118.0,0.0,6277.0,18.798789
559,0,1,1,0.0,4180,2306.0,182.0,1.0,6486.0,28.060438
598,1,1,1,1.0,9963,0.0,180.0,1.0,9963.0,18.066847
235,1,1,1,0.0,5500,1260.0,170.0,1.0,6760.0,25.147929
145,0,1,1,0.0,2330,4486.0,100.0,1.0,6816.0,14.671362

##### Our Final Dataframes for both train and test
- Drop that old variables before OneHotEncoding
- Computed OneHotEncoding columns
- Convert them into dataframes
- Append both of them to create final_dataframe

In [246]:
X_train = X_train.reset_index(drop=True)
encoded_train_df= encoded_train_df.reset_index(drop=True)

In [254]:
X_train.head()

,Gender,Married,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Credit_History,TotalIncome,Loan_Income_Ratio
0,1,0,1,0,3254,0.0,50.0,1.0,3254.0,15.365704
1,1,1,1,0,3315,0.0,96.0,1.0,3315.0,28.959276
2,1,1,1,0,3340,1710.0,150.0,0.0,5050.0,29.702970
3,1,1,0,0,2653,1500.0,113.0,0.0,4153.0,27.209246
4,1,1,1,0,2620,2223.0,150.0,1.0,4843.0,30.972538

In [256]:
encoded_train_df.head()

,Dependents_0.0,Dependents_1.0,Dependents_2.0,Dependents_3.0,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Loan_Amount_Term_12.0,Loan_Amount_Term_36.0,Loan_Amount_Term_60.0,Loan_Amount_Term_84.0,Loan_Amount_Term_120.0,Loan_Amount_Term_180.0,Loan_Amount_Term_240.0,Loan_Amount_Term_300.0,Loan_Amount_Term_360.0,Loan_Amount_Term_480.0
0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [247]:
X_final_train=pd.concat([X_train,encoded_train_df],axis=1)

In [248]:
X_test = X_test.reset_index(drop=True)
encoded_test_df = encoded_test_df.reset_index(drop=True)

In [249]:
X_final_test=pd.concat([X_test,encoded_test_df],axis=1)

##### Check no of Final Datapoints 
- As our train and test data have the indices different and not in order 
- If We directly concat ,due to difference in indices there is chance our data may form duplicates 
- So to avoid that,we used reset_index and and then conact ,both sepearte datframes
- Done this for both Training and testing data

In [253]:
len(df)==len(X_final_train)+len(X_final_test)

True

In [257]:
print(X_train.shape)
print(X_test.shape)

(491, 10)
(123, 10)